-- ============================================================================
-- carrito_schema.sql
-- Esquema de Supabase (Postgres) para el carrito de compras de CraftHub.
-- Coincide exactamente con lo que ya espera carrito_router.py (no hay que
-- tocar ni una línea de ese archivo, solo crear las tablas).
--
-- Cómo usarlo:
--   1. Abre tu proyecto en supabase.com → SQL Editor → New query.
--   2. Pega y ejecuta este archivo completo.
--   3. Verifica en Table Editor que aparezcan "carritos" y "carrito_items".
-- ============================================================================

create table if not exists carritos (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  nombre      text not null default 'Mi carrito',
  created_at  timestamptz not null default now()
);

create table if not exists carrito_items (
  id               bigint generated by default as identity primary key,
  carrito_id       bigint not null references carritos(id) on delete cascade,
  producto_id      integer not null,
  nombre_producto  text not null,
  imagen_url       text default '',
  artesano         text default '',
  precio           numeric(10,2) not null default 0,
  cantidad         integer not null default 1,
  created_at       timestamptz not null default now()
);

create index if not exists idx_carritos_user_id on carritos (user_id);
create index if not exists idx_carrito_items_carrito_id on carrito_items (carrito_id);

-- ============================================================================
-- ROW LEVEL SECURITY — mismo criterio permisivo que ya usan tus otras tablas
-- (acceso con la anon key). Si conectas Supabase Auth más adelante, cambia
-- estas políticas para filtrar por auth.uid() = user_id.
-- ============================================================================
alter table carritos       enable row level security;
alter table carrito_items  enable row level security;

drop policy if exists "lectura publica carritos" on carritos;
create policy "lectura publica carritos" on carritos
  for select using (true);
drop policy if exists "insertar carritos" on carritos;
create policy "insertar carritos" on carritos
  for insert with check (true);
drop policy if exists "eliminar carritos" on carritos;
create policy "eliminar carritos" on carritos
  for delete using (true);

drop policy if exists "lectura publica carrito_items" on carrito_items;
create policy "lectura publica carrito_items" on carrito_items
  for select using (true);
drop policy if exists "insertar carrito_items" on carrito_items;
create policy "insertar carrito_items" on carrito_items
  for insert with check (true);
drop policy if exists "actualizar carrito_items" on carrito_items;
create policy "actualizar carrito_items" on carrito_items
  for update using (true);
drop policy if exists "eliminar carrito_items" on carrito_items;
create policy "eliminar carrito_items" on carrito_items
  for delete using (true);

-- Fin del esquema. No lleva datos de ejemplo: el carrito se crea solo la
-- primera vez que un usuario entra (ver CarritoProvider.cargarCarritos →
-- _crearCarritoInicial en el frontend).
