-- ============================================================================
-- eventos_schema.sql
-- Esquema de Supabase (Postgres) para la pantalla de calendario de eventos
-- artesanales (comprador/vendedor) de CraftHub.
--
-- Cómo usarlo:
--   1. Abre tu proyecto en supabase.com → SQL Editor → New query.
--   2. Pega y ejecuta este archivo completo (crea tablas, RLS y datos demo).
--   3. En tu FastAPI (BACK/CraftHub), crea un router "eventos_router.py" que
--      use `supabase.table("eventos").select(...)` igual que productos_router.py.
--      Para traer el organizador embebido en un solo request (tal como lo
--      espera el modelo Flutter EventoArtesanal.fromJson), usa el embed de
--      PostgREST:
--
--        supabase.table("eventos") \
--          .select("*, organizador:organizadores_eventos(*)") \
--          .execute()
--
--      Eso arma automáticamente el JSON con la forma:
--        { ..., "organizador": { "nombre": ..., "telefono": ..., ... } }
--      que es exactamente lo que lee OrganizadorEvento.fromJson en el modelo
--      de Flutter (lib/models/evento_modelo.dart).
-- ============================================================================

-- ── 1. ORGANIZADORES (municipios, asociaciones, MICI, etc.) ────────────────
create table if not exists organizadores_eventos (
  id            bigint generated by default as identity primary key,
  nombre        text not null,
  tipo          text not null default 'Organización',
  telefono      text default '',
  whatsapp      text default '',
  email         text default '',
  sitio_web     text default '',
  foto_url      text default '',
  created_at    timestamptz not null default now()
);

-- ── 2. EVENTOS ──────────────────────────────────────────────────────────────
create table if not exists eventos (
  id                          bigint generated by default as identity primary key,
  titulo                      text not null,
  descripcion                 text default '',
  categoria                   text not null default 'Feria'
                              check (categoria in ('Feria','Taller','Exposición','Bazar','Festival','Mercado')),
  imagen_url                  text default '',
  fecha_inicio                timestamptz not null,
  fecha_fin                   timestamptz not null,
  ubicacion                   text not null,
  provincia                   text not null,
  latitud                     numeric(9,6) default 8.9824,
  longitud                    numeric(9,6) default -79.5199,
  es_gratuito                 boolean not null default true,
  precio_entrada              numeric(10,2) not null default 0,
  cupos_vendedor_total        integer not null default 0,
  cupos_vendedor_disponibles  integer not null default 0,
  -- Promoción de descuento (ej. 25% en algunos días del evento)
  descuento_porcentaje        integer check (descuento_porcentaje between 1 and 100),
  descuento_desde             date,
  descuento_hasta             date,
  organizador_id              bigint references organizadores_eventos(id) on delete set null,
  created_at                  timestamptz not null default now(),

  constraint eventos_fechas_validas check (fecha_fin >= fecha_inicio),
  constraint eventos_descuento_fechas_validas
    check (descuento_hasta is null or descuento_desde is null or descuento_hasta >= descuento_desde)
);

create index if not exists idx_eventos_fecha_inicio on eventos (fecha_inicio);
create index if not exists idx_eventos_provincia on eventos (provincia);
create index if not exists idx_eventos_categoria on eventos (categoria);

-- ── 3. FAVORITOS DE EVENTOS (comprador) ─────────────────────────────────────
create table if not exists eventos_favoritos (
  id          bigint generated by default as identity primary key,
  user_id     text not null,
  evento_id   bigint not null references eventos(id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (user_id, evento_id)
);

-- ── 4. SOLICITUDES DE ESPACIO DE VENDEDOR ───────────────────────────────────
create table if not exists eventos_solicitudes_vendedor (
  id           bigint generated by default as identity primary key,
  evento_id    bigint not null references eventos(id) on delete cascade,
  vendedor_id  text not null,
  mensaje      text default '',
  estado       text not null default 'pendiente'
               check (estado in ('pendiente','aceptada','rechazada')),
  created_at   timestamptz not null default now()
);

-- ============================================================================
-- ROW LEVEL SECURITY
-- Mismo criterio permisivo que ya usan las tablas "productos"/"favoritos"
-- (acceso con la anon key). Si más adelante conectas Supabase Auth, cambia
-- estas políticas para filtrar por auth.uid() = user_id.
-- ============================================================================
alter table organizadores_eventos      enable row level security;
alter table eventos                    enable row level security;
alter table eventos_favoritos          enable row level security;
alter table eventos_solicitudes_vendedor enable row level security;

-- create policy no soporta "if not exists" en Postgres, así que primero se
-- elimina la política si ya existe (esto hace que el script se pueda
-- volver a ejecutar sin error, por ejemplo si lo corriste antes a medias).
drop policy if exists "lectura publica organizadores" on organizadores_eventos;
create policy "lectura publica organizadores" on organizadores_eventos
  for select using (true);

drop policy if exists "lectura publica eventos" on eventos;
create policy "lectura publica eventos" on eventos
  for select using (true);
drop policy if exists "insertar eventos" on eventos;
create policy "insertar eventos" on eventos
  for insert with check (true);
drop policy if exists "actualizar eventos" on eventos;
create policy "actualizar eventos" on eventos
  for update using (true);

drop policy if exists "lectura publica favoritos" on eventos_favoritos;
create policy "lectura publica favoritos" on eventos_favoritos
  for select using (true);
drop policy if exists "insertar favoritos" on eventos_favoritos;
create policy "insertar favoritos" on eventos_favoritos
  for insert with check (true);
drop policy if exists "eliminar favoritos" on eventos_favoritos;
create policy "eliminar favoritos" on eventos_favoritos
  for delete using (true);

drop policy if exists "lectura publica solicitudes" on eventos_solicitudes_vendedor;
create policy "lectura publica solicitudes" on eventos_solicitudes_vendedor
  for select using (true);
drop policy if exists "insertar solicitudes" on eventos_solicitudes_vendedor;
create policy "insertar solicitudes" on eventos_solicitudes_vendedor
  for insert with check (true);

-- ============================================================================
-- DATOS DEMO — organizadores reales (entidades panameñas conocidas)
-- ============================================================================
insert into organizadores_eventos (nombre, tipo, telefono, whatsapp, email, sitio_web) values
  ('Municipio de Panamá',                     'Entidad gubernamental', '+507 512-8000', '50751280000', 'eventos@mupa.gob.pa',       'https://mupa.gob.pa'),
  ('Autoridad de Turismo de Panamá (ATP)',    'Entidad gubernamental', '+507 526-7000', '50752670000', 'info@atp.gob.pa',           'https://visitpanama.com'),
  ('Artesanías de Panamá',                    'Asociación de artesanos', '+507 315-4444', '50763154444', 'contacto@artesaniaspanama.org', 'https://artesaniaspanama.org'),
  ('Cámara de Comercio, Industrias y Agricultura de Panamá (CCIAP)', 'Cámara de comercio', '+507 207-3200', '50762073200', 'expocomer@panacamara.com', 'https://expocomer.com'),
  ('Municipio de Las Tablas',                 'Entidad gubernamental', '+507 994-6535', '50769946535', 'info@lastablas.gob.pa',     'https://lastablas.gob.pa'),
  ('Municipio de Boquete',                    'Entidad gubernamental', '+507 720-1440', '50767201440', 'turismo@boquete.gob.pa',    'https://boquete.gob.pa')
on conflict do nothing;

-- ============================================================================
-- DATOS DEMO — eventos reales de la cultura panameña (fechas de temporada
-- aproximadas; confirma las fechas exactas de cada edición 2026 con la ATP
-- o el municipio correspondiente antes de usarlas en producción, ya que
-- varias de estas ferias mueven su fecha exacta cada año).
-- ============================================================================
insert into eventos (
  titulo, descripcion, categoria, imagen_url, fecha_inicio, fecha_fin,
  ubicacion, provincia, latitud, longitud, es_gratuito, precio_entrada,
  cupos_vendedor_total, cupos_vendedor_disponibles,
  descuento_porcentaje, descuento_desde, descuento_hasta,
  organizador_id
) values
  (
    'Festival Nacional de la Pollera',
    'Celebración del traje típico panameño con desfiles, concursos y venta de polleras y accesorios artesanales.',
    'Festival',
    'https://images.unsplash.com/photo-1531058020387-3be344556be6?w=900',
    '2026-07-17 09:00:00-05', '2026-07-19 22:00:00-05',
    'Las Tablas, Los Santos', 'Los Santos', 7.7608, -80.2792,
    true, 0, 80, 22, null, null, null,
    (select id from organizadores_eventos where nombre = 'Municipio de Las Tablas')
  ),
  (
    'Feria de las Flores y del Café',
    'Exhibición de flores, café de altura y artesanías de la región de Boquete.',
    'Feria',
    'https://images.unsplash.com/photo-1533903345306-15d1c30952de?w=900',
    '2027-01-13 09:00:00-05', '2027-01-17 18:00:00-05',
    'Boquete, Chiriquí', 'Chiriquí', 8.7833, -82.4333,
    false, 5.00, 100, 40,
    25, '2027-01-15', '2027-01-17',
    (select id from organizadores_eventos where nombre = 'Municipio de Boquete')
  ),
  (
    'EXPOCOMER',
    'Feria multisectorial con pabellón de artesanías y productos hechos en Panamá.',
    'Feria',
    'https://images.unsplash.com/photo-1528444702795-51c1b6da1d05?w=900',
    '2027-03-10 09:00:00-05', '2027-03-12 19:00:00-05',
    'Centro de Convenciones Atlapa, Ciudad de Panamá', 'Panamá', 8.9880, -79.4877,
    false, 3.00, 60, 15, null, null, null,
    (select id from organizadores_eventos where nombre = 'Cámara de Comercio, Industrias y Agricultura de Panamá (CCIAP)')
  ),
  (
    'Festival del Diablico Sucio (Corpus Christi)',
    'Tradición de danzas y máscaras talladas a mano declarada Patrimonio Cultural, con venta de máscaras artesanales.',
    'Festival',
    'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=900',
    '2027-05-27 10:00:00-05', '2027-05-29 22:00:00-05',
    'La Villa de Los Santos, Los Santos', 'Los Santos', 7.9422, -80.3936,
    true, 0, 40, 9, null, null, null,
    (select id from organizadores_eventos where nombre = 'Autoridad de Turismo de Panamá (ATP)')
  ),
  (
    'Feria de Artesanías de Panamá',
    'La feria artesanal más grande del país: más de 100 talleres de las 10 provincias y comarcas.',
    'Feria',
    'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=900',
    '2026-08-14 09:00:00-05', '2026-08-18 18:00:00-05',
    'Casco Antiguo, Ciudad de Panamá', 'Panamá', 8.9518, -79.5347,
    true, 0, 120, 30,
    25, '2026-08-17', '2026-08-18',
    (select id from organizadores_eventos where nombre = 'Artesanías de Panamá')
  ),
  (
    'Festival de la Mejorana',
    'El festival folclórico más antiguo de Panamá: música típica, danza y artesanía tradicional de Los Santos.',
    'Festival',
    'https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=900',
    '2026-09-22 10:00:00-05', '2026-09-26 22:00:00-05',
    'Guararé, Los Santos', 'Los Santos', 7.8039, -80.2761,
    true, 0, 50, 12, null, null, null,
    (select id from organizadores_eventos where nombre = 'Municipio de Las Tablas')
  );

-- Fin del esquema. Verifica en el panel de Supabase (Table Editor) que las
-- tablas y los datos demo se hayan creado correctamente.
