-- ============================================================================
-- favoritos_artesanos_schema.sql
-- Esquema de Supabase (Postgres) para que un comprador marque artesanos
-- (vendedores) como favoritos. Coincide con lo que espera artesanos_router.py.
--
-- Cómo usarlo:
--   1. Abre tu proyecto en supabase.com → SQL Editor → New query.
--   2. Pega y ejecuta este archivo completo.
--   3. Verifica en Table Editor que aparezca "favoritos_artesanos".
-- ============================================================================

create table if not exists favoritos_artesanos (
  id           bigint generated by default as identity primary key,
  user_id      text not null,        -- comprador que marca el favorito
  artesano_id  text not null,        -- perfiles.user_id del vendedor
  created_at   timestamptz not null default now(),
  unique (user_id, artesano_id)
);

create index if not exists idx_favoritos_artesanos_user_id on favoritos_artesanos (user_id);
create index if not exists idx_favoritos_artesanos_artesano_id on favoritos_artesanos (artesano_id);

-- ============================================================================
-- ROW LEVEL SECURITY — mismo criterio permisivo que ya usan tus otras tablas.
-- ============================================================================
alter table favoritos_artesanos enable row level security;

drop policy if exists "lectura favoritos_artesanos" on favoritos_artesanos;
create policy "lectura favoritos_artesanos" on favoritos_artesanos
  for select using (true);
drop policy if exists "insertar favoritos_artesanos" on favoritos_artesanos;
create policy "insertar favoritos_artesanos" on favoritos_artesanos
  for insert with check (true);
drop policy if exists "eliminar favoritos_artesanos" on favoritos_artesanos;
create policy "eliminar favoritos_artesanos" on favoritos_artesanos
  for delete using (true);
