-- ============================================================================
-- tarjetas_guardadas_schema.sql
-- Esquema de Supabase (Postgres) para las tarjetas de pago guardadas de un
-- comprador. Coincide exactamente con lo que espera tarjetas_router.py (no
-- hay que tocar ni una línea de ese archivo, solo crear la tabla).
--
-- IMPORTANTE: esta tabla NUNCA guarda el número completo de la tarjeta ni el
-- CVV — solo datos enmascarados (marca, últimos 4 dígitos, titular,
-- vencimiento). tarjetas_router.py ni siquiera acepta esos campos en el
-- body del request, así que no hay forma de que lleguen aquí por error.
--
-- También agrega la columna "idioma" a la tabla "perfiles" (preferencia de
-- idioma del usuario — no traduce la app, solo guarda la preferencia).
--
-- Cómo usarlo:
--   1. Abre tu proyecto en supabase.com → SQL Editor → New query.
--   2. Pega y ejecuta este archivo completo.
--   3. Verifica en Table Editor que aparezca "tarjetas_guardadas" y que
--      "perfiles" tenga la columna "idioma".
-- ============================================================================

create table if not exists tarjetas_guardadas (
  id                bigint generated by default as identity primary key,
  user_id           text not null,
  marca             text not null,                 -- 'Visa' | 'Mastercard' | 'Amex' | 'Otra'
  ultimos_4         text not null,                  -- exactamente 4 dígitos
  nombre_titular    text not null,
  mes_vencimiento   integer not null,               -- 1-12
  anio_vencimiento  integer not null,
  alias             text,                           -- opcional, ej. "Tarjeta personal"
  predeterminada    boolean not null default false,
  created_at        timestamptz not null default now()
);

create index if not exists idx_tarjetas_guardadas_user_id on tarjetas_guardadas (user_id);

-- ============================================================================
-- ROW LEVEL SECURITY — mismo criterio permisivo que ya usan tus otras tablas
-- (acceso con la anon key; el backend filtra por user_id en cada consulta
-- porque no reenvía el JWT del usuario por request). Si conectas sesiones
-- reales más adelante, cambia estas políticas para filtrar por auth.uid().
-- ============================================================================
alter table tarjetas_guardadas enable row level security;

drop policy if exists "lectura tarjetas_guardadas" on tarjetas_guardadas;
create policy "lectura tarjetas_guardadas" on tarjetas_guardadas
  for select using (true);
drop policy if exists "insertar tarjetas_guardadas" on tarjetas_guardadas;
create policy "insertar tarjetas_guardadas" on tarjetas_guardadas
  for insert with check (true);
drop policy if exists "actualizar tarjetas_guardadas" on tarjetas_guardadas;
create policy "actualizar tarjetas_guardadas" on tarjetas_guardadas
  for update using (true);
drop policy if exists "eliminar tarjetas_guardadas" on tarjetas_guardadas;
create policy "eliminar tarjetas_guardadas" on tarjetas_guardadas
  for delete using (true);

-- ============================================================================
-- Preferencia de idioma en "perfiles" (tabla ya existente, sin schema file
-- propio — se agrega la columna acá porque no hay otro lugar documentado).
-- ============================================================================
alter table perfiles add column if not exists idioma text default 'es';
